### ISSUE TITLE
Strange Push to Origin behavior

### ISSUE THREAD

**Issue by tommytran732** [flathub/io.github.shiftey.Desktop#10]
When I push a change to origin, it keeps getting stuck on "Hanging on":

![image](https://user-images.githubusercontent.com/57488583/129340466-f19324c8-758f-437e-8ef2-014ee2361373.png)

However, as soon as I focus on another window, then switch back to it, it immediately starts pushing. I am not sure why it is doing this so it would be great if you could have a look.

**Comment by advaithm** [comment]
I am unfortunately unable to reproduce this issue.

**Comment by tommytran732** [comment]
Hm... So I did a little digging and it seems like this is an issue with GitHub Desktop itself:

https://github.com/shiftkey/desktop/issues/508
https://github.com/shiftkey/desktop/issues/573

I guess I should close the issue report here, since it is not an issue with the Flatpak package itself.
