### ISSUE TITLE
Core dump when attempting to run Flatpak-ed GitHub Desktop

### ISSUE THREAD

**Issue by worldofgeese** [flathub/io.github.shiftey.Desktop#110]
On Clear Linux, running GitHub Desktop installed from Flathub results in an instant crash with the message

```console
❯ flatpak run io.github.shiftey.Desktop 
Segmentation fault (core dumped)
```

**Comment by Lunarequest** [comment]
this is a issue that is in flatpak not github desktop, probably the aggressive compile clear linux uses crashed flatpak

**Comment by rokejulianlockhart** [comment]
> this is a issue that is in flatpak not github desktop

Shouldn't we introspect the core dump to verify that? Could you at least upload it for posterity, @worldofgeese?
