### ISSUE TITLE
Access to SDKs from the app

### ISSUE THREAD

**Issue by SantiagoPaak** [flathub/io.github.shiftey.Desktop#119]
Dunno if I'm just misunderstanding how Flatpak works.

Trying to use GitHub desktop with a project that runs some verification hooks using Husky. It fails, because it can't find the programs.

A solution would be to have access to the node sdk and use a path to make it search the binaries there. Tried to do that but the SDK doesn't appear in the internal filesystem. Is that something that it must be done from here or there's something I'm not doing right?

**Comment by Lunarequest** [comment]
there's a issue with how node etc is accessed outside flatpaks, and how git hooks work, we probably need to get a change upstream in git to allow hooks to be overridden so we can pass paths of things like nodes etc

**Comment by Lunarequest** [comment]
closing this as its the same as #94 and #94 contains an explanation of what needs to be done
