### ISSUE TITLE
Incorrect package name

### ISSUE THREAD

**Issue by tommytran732** [flathub/io.github.shiftey.Desktop#12]
I don't know if this is too late for this or not but I just realized the package name is wrong. It should be io.github.shiftkey.Desktop, not io.github.shiftey.Desktop. The k in "shiftkey" is missing :(

**Comment by advaithm** [comment]
Ah I'll fix it.

**Comment by Lunarequest** [comment]
I just haven't had time to fix this and upstream doesn't really have a issue
