### ISSUE TITLE
White screen 3.3.5-linux1

### ISSUE THREAD

**Issue by ragardner** [flathub/io.github.shiftey.Desktop#137]
Hello,

I think I am experiencing this bug https://github.com/shiftkey/desktop/issues/958

pop os fully up to date
app version 3.3.5-linux1

**Comment by shiftkey** [comment]
I suspect https://github.com/flathub/io.github.shiftey.Desktop/pull/136 will fix this for you when it's merged

**Comment by Sjoerd1993** [comment]
It's likely indeed that #136 will fix it, although it's running into some issues with electron during the build:

```
verbose 6.565236314 Error: Can't make a request in offline mode ("https://registry.yarnpkg.com/electron/-/electron-26.2.4.tgz")
    at RequestManager.request (/run/build/github-desktop/vendor/yarn-1.21.1.js:78236:29)
    at /run/build/github-desktop/vendor/yarn-1.21.1.js:32811:43
    at Generator.next (<anonymous>)
    at step (/run/build/github-desktop/vendor/yarn-1.21.1.js:310:30)
    at /run/build/github-desktop/vendor/yarn-1.21.1.js:328:14
    at new Promise (<anonymous>)
    at new F (/run/build/github-desktop/vendor/yarn-1.21.1.js:25783:28)
    at /run/build/github-desktop/vendor/yarn-1.21.1.js:307:12
    at NpmRegistry.request (/run/build/github-desktop/vendor/yarn-1.21.1.js:32838:7)
    at /run/build/github-desktop/vendor/yarn-1.21.1.js:76175:31

```


In the meantime, you can downgrade temporarily:
`flatpak remote-info --log flathub io.github.shiftey.Desktop` should give you a bunch of logs and commits.
Then you can downgrade to a specific commit using something like:
`sudo flatpak update --commit=91f4274313a1c6702fa1ce365e40e14ee474055af1c00a7bad2776d2a921972e io.github.shiftey.Desktop` (root is needed)

Note that it will update to the latest version with the first update. Apparently you can prevent this by masking the flatpak (`flatpak mask io.github.shiftey.Desktop`), but personally I've not done so.

**Comment by rizitis** [comment]
That worked for now...

**Comment by Lunarequest** [comment]
I asked a friend to look at it, and immediately realised the source upgrade didn't happen due to a rebase which broke stuff sorry for the delay

**Comment by Lunarequest** [comment]
updated has been pushed will take a bit for the updates to spread through the caches
