### ISSUE TITLE
Application Failing to Start After Updating / Installing Through Flatpak

### ISSUE THREAD

**Issue by misimpso** [flathub/io.github.shiftey.Desktop#16]
### Operating System/Distribution

Which distribution of Linux are you using?
Pop_OS! 21.04

### Installer

Which version of the app? 2.9.3
Which installer type? Flatpak

### What happened?
Had installed application through Flatpak and was running just fine on version 2.9.2. Updated application to 2.9.3 and was now getting an error preventing application from starting up. Error message reads:
``` shell
$ flatpak run io.github.shiftey.Desktop                                                                                                                                                                      
gpg-agent: a gpg-agent is already running - not starting a new one
/app/bin/zypak-helper: /usr/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /app/bin/zypak-helper)
/app/bin/zypak-helper: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /app/bin/zypak-helper)
/app/bin/zypak-helper: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.13' not found (required by /app/bin/zypak-helper)
```
Uninstalled and reinstalled application a number of times through flatpak and still ran into the same problem. Decided to install the 2.9.2 and 2.9.3 debian packages from the releases page on this Github repo, and the application starts just fine.

---
Cross-post from: https://github.com/shiftkey/desktop/issues/600

**Comment by Lunarequest** [comment]
I think I know what's wrong. I'll push out an update right away

**Comment by misimpso** [comment]
Reinstalled through flatpak and it looks to be working now. Thank you for fixing the issue!
