### ISSUE TITLE
Unable to sign-in

### ISSUE THREAD

**Issue by geloczigeri** [flathub/io.github.shiftey.Desktop#32]
### System
Operating System: Manjaro Linux
KDE Plasma Version: 5.24.2
KDE Frameworks Version: 5.91.0
Qt Version: 5.15.2
Kernel Version: 5.15.25-1-MANJARO (64-bit)
Graphics Platform: X11
Processors: 16 × AMD Ryzen 7 3700X 8-Core Processor
Memory: 31,3 GiB of RAM
Graphics Processor: NVIDIA GeForce GTX 1080/PCIe/SSE2

### Browser
Firefox 97.0.1
also tried with latest Chromium

### GitHub Desktop version
[2.9.9-linux1 from Flathub](https://flathub.org/apps/details/io.github.shiftey.Desktop)

### Steps to reproduce
1. Install Manjaro, with KDE desktop environment and enable Flatpak support
2. Install GitHub Desktop: `flatpak install flathub io.github.shiftey.Desktop`
3. Start GitHub Desktop
4. Try to login
5. Firefox opens
6. Enter credentials, login to github.com
7. When Firefox asks permission to open the link with an app, accept it and let GitHub Desktop open it
8. GitHub Desktop gets focused, but does nothing

Same thing happens when I trigger login from the Options menu:
1. Open GitHub Desktop
2. Click File -> Options...
3. Click Accounts -> GitHub.com -> Sign in
4. Continue with browser
5. Firefox opens
6. Enter credentials, login to github.com
7. When Firefox asks permission to open the link with an app, accept it and let GitHub Desktop open it
8. GitHub Desktop gets focused, but does nothing

![image](https://user-images.githubusercontent.com/3268224/155977049-018f1d64-bae6-46ed-8655-8357f56148ce.png)

The loading icon at the top right corner in the "Sign in using your browser" dialog is just spinning.

**Comment by Lunarequest** [comment]
Can you check if `xdg-open` works?

**Comment by geloczigeri** [comment]
> Can you check if `xdg-open` works?

Hi,

Thanks for the quick reply :)
xdg-open is there, I see the following in my terminal:

```                                                                                                                                                                                                                             
xdg-open
   xdg-open -- opens a file or URL in the user's preferred
   application

Synopsis

   xdg-open { file | URL }

   xdg-open { --help | --manual | --version }

Use 'man xdg-open' or 'xdg-open --manual' for additional info.

```

**Comment by Fredolx** [comment]
I have the same problem on Fedora 35

**Comment by yetimaan** [comment]
Same on Elementary OS. It never signs in on Version 2.9.9-linux2.

**Comment by Lunarequest** [comment]
By any chance if your web browser a flatpakm

**Comment by yetimaan** [comment]
> By any chance if your web browser a flatpak?

No, I'm using Firefox from the Ubuntu repos.

**Comment by Lunarequest** [comment]
I tried reproducing this issue on NixOS, I can't reproduce this issue however due to flatpak sandbox stuff it can appear like it hasn't worked and takes a good half minute to a minute after the browser calls `xdg-open` for the flatpak to notice

**Comment by Fredolx** [comment]
> By any chance if your web browser a flatpak?

My browser was not a flatpak when the issue occured

**Comment by yetimaan** [comment]
> I tried reproducing this issue on NixOS, I can't reproduce this issue however due to flatpak sandbox stuff it can appear like it hasn't worked and takes a good half minute to a minute after the browser calls `xdg-open` for the flatpak to notice

OK, I'll give it a shot today. Will wait for a few minutes to see if the login takes.

**Comment by yetimaan** [comment]
@Lunarequest I let it sit for an hour - it never finished logging in.

**Comment by Lunarequest** [comment]
Yeah this appears to be a upatream issue https://github.com/shiftkey/desktop/issues/672 please head over to the upstream tracker.

**Comment by eylenburg** [comment]
This issue still persists. Upstream has closed the bug but I will comment there as well.
