### ISSUE TITLE
"Show in your File Manager" does not work

### ISSUE THREAD

**Issue by tommytran732** [flathub/io.github.shiftey.Desktop#4]
The button does nothing - it neither opens the project on nautilus nor open it in flatpak vscodium :/

**Comment by advaithm** [comment]
regarding the flatpak vscodium. due to the sandbox we can't see other flatpaks. I'll look into opening in the file manager

**Comment by tommytran732** [comment]
May I ask why? Can't we use the system handler somehow? It seems like flatpak apps can open each other just fine using it.

**Comment by advaithm** [comment]
github desktop detects and launches apps in a different way. we can't detect the flatpak apps since that would mean mounting the flatpak app dir which based on testing is blocked

**Comment by tommytran732** [comment]
Hm... I wonder if you have looked into flatpak-xdg-utils? https://github.com/flatpak/flatpak-xdg-utils
It looks like it can do flatpak-spawn

**Comment by advaithm** [comment]
we already use flatpak-spawn. We can't detect flatpak apps so even if they are installed we can't confirm it hence that's pretty much blocked off from the front end.

**Comment by tommytran732** [comment]
How about making an environment variable so the user can specify it themselves? That way you don't need to detect it

**Comment by tommytran732** [comment]
Plus, I am pretty sure flatpak apps can detect each other, flatseal does it just fine

**Comment by advaithm** [comment]
that would involve disabling a bunch of safety checks. I'm not sure upstream would be fine

**Comment by tommytran732** [comment]
I think it just does xdg-data/flatpak/app:ro

**Comment by advaithm** [comment]
#

> Plus, I am pretty sure flatpak apps can detect each other, flatseal does it just fine

this flatpak is already insanely permissive I don't really want to end up exposing more of the filesystem

**Comment by tommytran732** [comment]
> > Plus, I am pretty sure flatpak apps can detect each other, flatseal does it just fine
> 
> this flatpak is already insanely permissive I don't really want to end up exposing more of the filesystem

I don't think there would be anny security/privacy with doing xdg-data/flatpak/app:ro and /var/lib/flatpak/app:ro

That said, I do see some permission like, filesystem=host, and socket=pulseaudio being too permissive. Especially, the latter 2 - I kind of wonder why the app would need them. As for the filesystem=host, I think that's more problematic than just doing xdg-data/flatpak/app:ro and xdg-documents... After all, the default location for projects are ~/Documents anyways.

Besides, even with filesystem=host, /var/lib/flatpak/app:ro cannot actually be read without you specifying it. Maybe that's the issue with the app not being able to detect other flatpak apps?

**Comment by advaithm** [comment]
`filesystem=host` is for non flatpak editor detection. `socket=pulseaudio` is something electron needs.

**Comment by tommytran732** [comment]
> `filesystem=host` is for non flatpak editor detection. `socket=pulseaudio` is something electron needs.

I don't think `socket=pulseaudio` is needed for electron at all. In fact, I am running both discord and github with socket=pulse audio off, and they work just fine (obviously I don't do voice chat with it).

But yeah, since you are already reading the `host`, I really don't see the problem with just reading /var/lib/flatpak. 

Plus, isn't /bin and /sbin blacklisted when you are using `host` anyways?

**Comment by advaithm** [comment]
> > `filesystem=host` is for non flatpak editor detection. `socket=pulseaudio` is something electron needs.
> 
> I don't think `socket=pulseaudio` is needed for electron at all. In fact, I am running both discord and github with socket=pulseaudio off, and they work just fine (obviously I don't do voice chat with discord).
> 
> But yeah, since you are already reading the `host`, I really don't see the problem with just reading /var/lib/flatpak.
> 
> Plus, isn't /bin and /sbin blacklisted when you are using `host` anyways?

/bin is usually just a symlink to /usr/bin which is under /var/run/host. I've got a pr adding this. would you mind testing

**Comment by tommytran732** [comment]
Sure, I will test it now

**Comment by advaithm** [comment]
just to be clear from looking over the source code, it only support vscodium in a flatpak

**Comment by tommytran732** [comment]
Okay, so a few things: 

1. You missed /var/lib/flatpak:ro in your file system permissions. The PR didn't even detect vscodium, but adding that permission fixed it.

2. Actually I made a mistake when I talked about xdg-data/flatpak/app... I tested without permission for  xdg-data/flatpak/app, and it worked fine (but it needs permission to read /var/lib/flatpak still)

3. Detect works fine with what I said in 1, but it doesn't actually open flatpak vscodium just like how it doesn't open nautilus installed on the host

**Comment by advaithm** [comment]
I pushed a second commit adding the permission the second build should auto detect now. I'll look into the launching in a bit

**Comment by tommytran732** [comment]
Could you also try disabling the pulseaudio socket while we're at it (maybe after you are done fixing the launching problem)? I tested it without pulse audio and it worked just fine ¯\_(ツ)_/¯

**Comment by advaithm** [comment]
@tommytran732 mind testing the latest build

**Comment by advaithm** [comment]
@tommytran732 could you check if you have  default file manager set? if not try setting it to another one and back. Under the hood electron should be using xdg-open which will work unless a default file manager is not set

**Comment by advaithm** [comment]
after some more testing your issue stems from a default file manager not being set, I'm closing this issue.
