### ISSUE TITLE
User Interaction Failed

### ISSUE THREAD

**Issue by rbharathkumar** [flathub/io.github.shiftey.Desktop#48]
Hi Team,
I have been receiving the below mentioned error while trying to pull/push items from GitHub desktop.

![image](https://user-images.githubusercontent.com/38585383/166183544-629170e3-a9f9-4749-86be-cfd77f17e065.png)

**Environment:**
OS - MX Linux
Desktop - KDE

I do have gnome-keyring installed since I was receiving some error about logins.

The flatpak is upto date.
```shell
$ flatpak list
Name                          Application ID                               Version                      Branch         Installation
GitHub Desktop                io.github.shiftey.Desktop                    release-3.0.0-linux1         stable         system
```

Kindly let me know if I can help with any other information.

**Comment by Lunarequest** [comment]
It looks like gnome-keyring isn't being unlocked. Thats usually why the error occurs.

**Comment by rbharathkumar** [comment]
Is there anything that can be done from the user side to resolve the issue ?
Any setting to change or something ?

**Comment by Lunarequest** [comment]
I have no idea. I think this is an upstream issue
