### ISSUE TITLE
xdg-open do not work for Flatpak package (Deepin 20.6/Debian 10)

### ISSUE THREAD

**Issue by eduardomozart** [flathub/io.github.shiftey.Desktop#60]
### The problem

I installed the Flatpak package but when I click to sign-in it opens the browser and when I click at "xdg-open" a new window is open with a new GitHub Desktop instance instead of logging in.

### Release version

3.0.0-linux1 (x64)

### Operating system

Deepin 20.6 (Debian 10)

**Comment by Lunarequest** [comment]
Which browser do you use. With firefox I'm able to login everytime but with chromium based browsers it's very hit or miss

**Comment by eduardomozart** [comment]
I’m using Google Chrome. I ended up using the *.deb package to get it working.

**Comment by Lunarequest** [comment]
it looks like this commit broke things for debian 10 https://github.com/flathub/io.github.shiftey.Desktop/commit/3e3592f244889589a86407bc7ebf7ce1dee584af it boils down to debian 10 shipping an outdated version of flatpak(you can use backports to get a new compatible one) I'll revert it and get a working ver out now

**Comment by eduardomozart** [comment]
Hello, @Lunarequest 
Thank you for your response! I'll wait the Flathub report the new version and I'll test it as soon as it's available, so I return here to say if this works.

**Comment by Lunarequest** [comment]
it should be out by now(if it isn't its probably just taking time for it to distribute)

**Comment by eduardomozart** [comment]
After installing the new version I can confirm that it started working again. Thank you!
