### ISSUE TITLE
i dont seem to be able to select more than just neovim for my editor

### ISSUE THREAD

**Issue by pyrotek45** [flathub/io.github.shiftey.Desktop#9]
neovim seems to be the only selection of editors i can choose from and clicking (open file in neovim doesn't seem to work either.

I have other editors installed as well, including vs code and gedit, but they don't appear in the selection menu.

**Comment by shiftkey** [comment]
The supported editors that the app detects are listed here: https://github.com/shiftkey/desktop/blob/5e0e77ba14897f97598a5a0e2d6cefab0f9b4c41/app/src/lib/editors/linux.ts#L18-L66

Contributions are welcome for additional editors - it's very much an allow-list approach and the docs here have some more context: https://github.com/shiftkey/desktop/blob/linux/docs/technical/editor-integration.md#linux

**Comment by advaithm** [comment]
if you have flatpaked editors I have a pr that someone can test for this
