### ISSUE TITLE
Git hooks that call external programs do not work in Flatpak

### ISSUE THREAD

**Issue by aminya** [flathub/io.github.shiftey.Desktop#94]
### The problem

I am not sure where I should open this issue, but in case Flatpak is supported here:

When using the Flatpak version of GitHub Desktop, the Git hooks that call the external programs (e.g. Node, npm, yarn, etc.), will not work. The program cannot call them.

### Release version

3.1.5-linux2

### Operating system

Kubuntu 22.10

### Steps to reproduce the behavior

1. Create a git hook (e.g. using Husky)
2. Call an external program inside the hook

### Additional context

https://github.com/shiftkey/desktop/issues/828

**Comment by Lunarequest** [comment]
I believe this should be expected(git hooks link to /usr/ which doesn't exist in the flatpak), could you try running it from CLI and see if git outputs anything?

**Comment by aminya** [comment]
Yes, the git hooks work as expected from the CLI, but I'd like to use GitHub Desktop for committing. This now blocks the commit feature.

**Comment by Lunarequest** [comment]
from the cli I mean running flatpak from the cli like 
```
$ flatpak run io.github.shiftey.Desktop/
```
Along with this try
```
$ flatpak run --devel --command=sh io.github.shiftey.Desktop 
```
this will give you a sh shell inside the sandbox. You might be able to get more debugable info. I doubt it would be possible to support git hooks probably ever due to the way the sandbox works.

**Comment by Lunarequest** [comment]
After looking into this, git hooks are spawned inside the sandbox and as a result don't work there is no work around as this would require major changes to now git handles hooks

**Comment by StuartJAtkinson** [comment]
I have found this issue. Is it non-fixable? It finds the external editor fine.

**Comment by aminya** [comment]
@Lunarequest If you are deciding to close the issue as not planned, please consider adding this downside to the Flatpak readme or description.
